# ============================================================
# generate-photo-data.ps1
# Converts all photos in assets/gallery/ to compressed base64
# data URLs and writes them to photo-data.js.
#
# Uses .NET System.Drawing to resize photos to a smaller
# dimension suitable for the keepsake card (max 300px).
# ============================================================

Add-Type -AssemblyName System.Drawing

$galleryDir = Join-Path $PSScriptRoot "assets\gallery"
$outputFile = Join-Path $PSScriptRoot "photo-data.js"

# Photo filenames in the order they appear in gallery.js
$photoFiles = @(
    "photo1.jpg", "photo2.jpg", "photo3.jpg", "photo4.jpg",
    "photo5.jpg", "photo6.jpg", "photo7.jpg", "photo8.jpg",
    "photo9.jpg", "photo10.jpg", "photo11.jpg", "photo12.jpg",
    "photo13.jpg", "photo14.jpg", "photo15.jpg", "photo16.jpg",
    "photo17.jpg", "photo18.jpg", "photo19.jpg", "photo20.jpg",
    "photo21.jpeg", "photo23.jpeg", "photo25.jpeg"
)

$maxDim = 300  # max width/height for the card thumbnail
$jpegQuality = 60  # JPEG compression quality (0-100)

# Set up JPEG encoder with quality parameter
$jpegCodec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object { $_.MimeType -eq 'image/jpeg' }
$encoderParams = New-Object System.Drawing.Imaging.EncoderParameters(1)
$encoderParams.Param[0] = New-Object System.Drawing.Imaging.EncoderParameter(
    [System.Drawing.Imaging.Encoder]::Quality, [long]$jpegQuality
)

$entries = @()

foreach ($file in $photoFiles) {
    $filePath = Join-Path $galleryDir $file
    if (-not (Test-Path $filePath)) {
        Write-Host "  SKIP (not found): $file" -ForegroundColor Yellow
        $entries += "  null"
        continue
    }

    Write-Host "  Processing: $file" -NoNewline

    try {
        $original = [System.Drawing.Image]::FromFile($filePath)

        # Calculate new dimensions keeping aspect ratio
        $w = $original.Width
        $h = $original.Height
        if ($w -gt $h) {
            $newW = $maxDim
            $newH = [int]([math]::Round($h * ($maxDim / $w)))
        } else {
            $newH = $maxDim
            $newW = [int]([math]::Round($w * ($maxDim / $h)))
        }

        # Resize
        $resized = New-Object System.Drawing.Bitmap($newW, $newH)
        $graphics = [System.Drawing.Graphics]::FromImage($resized)
        $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
        $graphics.DrawImage($original, 0, 0, $newW, $newH)

        # Save to memory stream as compressed JPEG
        $ms = New-Object System.IO.MemoryStream
        $resized.Save($ms, $jpegCodec, $encoderParams)
        $bytes = $ms.ToArray()
        $base64 = [Convert]::ToBase64String($bytes)
        $dataUrl = "data:image/jpeg;base64,$base64"

        $sizeKB = [math]::Round($bytes.Length / 1024, 1)
        Write-Host " -> ${newW}x${newH}, ${sizeKB}KB" -ForegroundColor Green

        $entries += "  `"$dataUrl`""

        # Cleanup
        $ms.Dispose()
        $graphics.Dispose()
        $resized.Dispose()
        $original.Dispose()
    }
    catch {
        Write-Host " -> ERROR: $_" -ForegroundColor Red
        $entries += "  null"
    }
}

# Write the JS file
$jsContent = @"
/* =============================================================
   photo-data.js — Auto-generated by generate-photo-data.ps1
   Contains base64 data URLs of all gallery photos, resized to
   thumbnail size for the keepsake card download feature.
   
   These data URLs are same-origin, so they won't taint the
   canvas even when the page is opened via file:// protocol.
   
   DO NOT EDIT MANUALLY. Re-run generate-photo-data.ps1 to
   regenerate after adding/changing photos.
============================================================= */
// eslint-disable-next-line no-unused-vars
var PHOTO_DATA_URLS = [
$($entries -join ",`n")
];
"@

Set-Content -Path $outputFile -Value $jsContent -Encoding UTF8
$fileSizeKB = [math]::Round((Get-Item $outputFile).Length / 1024)
Write-Host "`nDone! Written to photo-data.js (${fileSizeKB}KB)" -ForegroundColor Cyan
